apiVersion: v1
kind: ConfigMap
metadata:
  name: chain-gateway-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "chain-gateway.npool.top"
      http_port: 50580
      grpc_port: 50581
      healthz_port: 50582
      prometheus_port: 50583
      appid: "89089012783789789719823798127398"
      serviceid: "94f9147c-60f0-11ed-b341-97315b5d37ad"
      logdir: "./"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
