apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chain-gateway-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: chain-gateway-traefik-app
    k8s.kuboard.cn/workload: chain-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-chain-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/chain/v1/get/appcoins
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coindescriptions
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coincurrencies
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coincurrency
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/fiatcurrency
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/fiatcurrencies
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coinfiatcurrencies
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/fiatcurrencytypes
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coinfiatcurrencyhistories
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/fiatcurrencyhistories
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coincurrencyhistories
            backend:
              serviceName: chain-gateway
              servicePort: 50580
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.procyon.npool.top
      http: *http_rules
    - host: api.lpsb.npool.top
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chain-gateway-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: chain-gateway-traefik-app
    k8s.kuboard.cn/workload: chain-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-chain-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/chain/v1/create/appcoin
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/update/appcoin
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/delete/appcoin
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/n/appcoins
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/coindescription
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/update/coindescription
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/app/coindescription
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/app/coindescriptions
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/txs
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coins
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/update/coin
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/coin
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/fiatcurrencytype
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/update/fiatcurrencytype
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/fiat
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/update/fiat
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/fiats
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/fiatcurrencyfeed
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/update/fiatcurrencyfeed
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/fiatcurrencyfeeds
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coincurrencyfeeds
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/coincurrencyfeed
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/update/coincurrencyfeed
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/coinfiat
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/delete/coinfiat
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coinfiats
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/chains
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/get/coinusedfors
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/create/coinusedfor
            backend:
              serviceName: chain-gateway
              servicePort: 50580
          - path: /api/chain/v1/delete/coinusedfor
            backend:
              serviceName: chain-gateway
              servicePort: 50580
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.procyon.npool.top
      http: *http_rules
    - host: api.lpsb.npool.top
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules
